apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: Go_RunTime
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: Go_RunTime 
  name: Go_RunTime
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: Go_RunTime 
